name = "message-sender"
main = "./dist/worker.mjs"
compatibility_date = "2022-05-17"

[env.staging]
name = "message-sender-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "message-sender"
vars = { ENVIRONMENT = "production" }
workers_dev = false
route = "message-sender.api.nurliman.dev/*"