name = "message-sender"
main = "build/worker/shim.mjs"
compatibility_date = "2022-05-17"

[vars]
MESSAGE_RECIPIENT_EMAIL = "nurlimand@gmail.com"
MESSAGE_RECIPIENT_NAME = "Nurliman Diara A"
WORKERS_RS_VERSION = "0.0.9"
ENVIRONMENT = "development"

[build]
command = "worker-build --release"

[env.staging]
name = "message-sender-staging"

[env.staging.vars]
MESSAGE_RECIPIENT_EMAIL = "nurlimand@gmail.com"
MESSAGE_RECIPIENT_NAME = "Nurliman Diara A"
WORKERS_RS_VERSION = "0.0.9"
ENVIRONMENT = "staging"

[env.production]
name = "message-sender"

[env.production.vars]
MESSAGE_RECIPIENT_EMAIL = "nurlimandiara@gmail.com"
MESSAGE_RECIPIENT_NAME = "Nurliman Diara A"
WORKERS_RS_VERSION = "0.0.9"
ENVIRONMENT = "production"