name = "message-sender"
main = "./src/index.ts"
compatibility_date = "2022-05-17"

[env.staging]
name = "message-sender-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "message-sender"
vars = { ENVIRONMENT = "production" }