name = "message-sender"
main = "build/worker/shim.mjs"
compatibility_date = "2022-05-17"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.staging]
name = "message-sender-staging"
vars = { WORKERS_RS_VERSION = "0.0.9", ENVIRONMENT = "staging" }

[env.production]
name = "message-sender"
vars = { WORKERS_RS_VERSION = "0.0.9", ENVIRONMENT = "production" }