/* eslint-disable */
/* prettier-ignore */

/**
 * THIS FILE IS GENERATED BY `scripts/build-jss.ts`.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
const styles: any = {
  ":where(html.dark) *, :where(html.dark) ::before, :where(html.dark) ::after": {
    "borderColor": "#27272a"
  },
  "::-moz-selection": {
    "color": "#fff",
    "background": "#f540cc"
  },
  "::selection": {
    "color": "#fff",
    "background": "#f540cc"
  }
};

export default styles;
