/* eslint-disable */
/* prettier-ignore */

/**
 * THIS FILE IS GENERATED BY `scripts/build-jss.ts`.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
const styles: any = {
  ":is(:where(.dark) *),:is(:where(.dark) \n)::before,:is(:where(.dark) \n)::after": {
    "--tw-border-opacity": "1",
    "borderColor": "rgb(39 39 42 / var(--tw-border-opacity))"
  }
};

export default styles;
