/* eslint-disable */
/* prettier-ignore */

/**
 * THIS FILE IS GENERATED BY `scripts/build-jss.ts`.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
const styles: any = {
  ":where(html.dark) *,:where(html.dark) :after,:where(html.dark) :before": {
    "borderColor": "#27272a"
  },
  "::-moz-selection": {
    "background": "#f540cc",
    "color": "#fff"
  },
  "::selection": {
    "background": "#f540cc",
    "color": "#fff"
  },
  "@media (prefers-color-scheme:dark)": {
    ":where(html:not(.light)) *,:where(html:not(.light)) :after,:where(html:not(.light)) :before": {
      "borderColor": "#27272a"
    }
  }
};

export default styles;
