/* eslint-disable */
/* prettier-ignore */

/**
 * THIS FILE IS GENERATED BY `scripts/build-jss.ts`.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
const styles: any = {
  ".brutal-btn": {
    "transitionProperty": "background-color",
    "transitionTimingFunction": "cubic-bezier(0.4, 0, 0.2, 1)",
    "transitionDuration": "150ms"
  },
  ".brutal-btn,\n      .brutal-btn-white": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(255 255 255 / var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(0 0 0 / var(--tw-text-opacity))"
  },
  ".brutal-btn:hover,\n      .brutal-btn-white:hover": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(244 244 245 / var(--tw-bg-opacity))"
  },
  ".brutal-btn:active,\n      .brutal-btn-white:active": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(228 228 231 / var(--tw-bg-opacity))"
  },
  ".brutal-btn-white-pink": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(255 255 255 / var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(0 0 0 / var(--tw-text-opacity))"
  },
  ".brutal-btn-white-pink:hover": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(255 144 232 / var(--tw-bg-opacity))"
  },
  ".brutal-btn-white-pink:active": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(255 206 247 / var(--tw-bg-opacity))"
  },
  ".brutal-btn-zinc": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(228 228 231 / var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(255 255 255 / var(--tw-text-opacity))"
  },
  ".brutal-btn-zinc:hover": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(212 212 216 / var(--tw-bg-opacity))"
  },
  ".brutal-btn-zinc:active": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(161 161 170 / var(--tw-bg-opacity))"
  },
  ".brutal-btn-teal": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(35 160 148 / var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(255 255 255 / var(--tw-text-opacity))"
  },
  ".brutal-btn-teal:hover": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(27 134 126 / var(--tw-bg-opacity))"
  },
  ".brutal-btn-teal:active": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(25 108 102 / var(--tw-bg-opacity))"
  },
  ".brutal-btn-bordered-sm": {
    "border": "1px solid rgba(0, 0, 0, 1)"
  },
  ".brutal-btn-bordered": {
    "border": "2px solid rgba(0, 0, 0, 1)"
  },
  ".brutal-btn-shadow-sm": {
    "boxShadow": "2px 2px 0px rgba(0, 0, 0, 1)"
  },
  ".brutal-btn-shadow-sm:active": {
    "boxShadow": "1px 1px 0px rgba(0, 0, 0, 1)",
    "transform": "translate3d(1px, 1px, 0px)"
  },
  ".brutal-btn-shadow": {
    "boxShadow": "4px 4px 0px rgba(0, 0, 0, 1)"
  },
  ".brutal-btn-shadow:active": {
    "boxShadow": "1px 1px 0px rgba(0, 0, 0, 1)",
    "transform": "translate3d(3px, 3px, 0px)"
  }
};

export default styles;
