/* eslint-disable */
/* prettier-ignore */

/**
 * THIS FILE IS GENERATED BY `scripts/build-jss.ts`.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
const styles: any = {
  ".brutal-btn": {
    "transitionDuration": ".15s",
    "transitionProperty": "background-color,box-shadow,transform",
    "transitionTimingFunction": "cubic-bezier(.4,0,.2,1)"
  },
  ".brutal-btn-white": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(255 255 255/var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(0 0 0/var(--tw-text-opacity))"
  },
  ".brutal-btn-white:hover": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(244 244 245/var(--tw-bg-opacity))"
  },
  ".brutal-btn-white:active": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(228 228 231/var(--tw-bg-opacity))"
  },
  ".brutal-btn-white:is(.dark *)": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(0 0 0/var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(255 255 255/var(--tw-text-opacity))"
  },
  ".brutal-btn-white:hover:is(.dark *)": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(24 24 27/var(--tw-bg-opacity))"
  },
  ".brutal-btn-white:active:is(.dark *)": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(9 9 11/var(--tw-bg-opacity))"
  },
  ".brutal-btn-white-pink": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(255 255 255/var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(0 0 0/var(--tw-text-opacity))"
  },
  ".brutal-btn-white-pink:hover": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(255 144 232/var(--tw-bg-opacity))"
  },
  ".brutal-btn-white-pink:active": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(255 206 247/var(--tw-bg-opacity))"
  },
  ".brutal-btn-zinc": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(228 228 231/var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(0 0 0/var(--tw-text-opacity))"
  },
  ".brutal-btn-zinc:hover": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(212 212 216/var(--tw-bg-opacity))"
  },
  ".brutal-btn-zinc:active": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(161 161 170/var(--tw-bg-opacity))"
  },
  ".brutal-btn-zinc:is(.dark *)": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(24 24 27/var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(255 255 255/var(--tw-text-opacity))"
  },
  ".brutal-btn-zinc:hover:is(.dark *)": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(9 9 11/var(--tw-bg-opacity))"
  },
  ".brutal-btn-zinc:active:is(.dark *)": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(0 0 0/var(--tw-bg-opacity))"
  },
  ".brutal-btn-teal": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(35 160 148/var(--tw-bg-opacity))",
    "--tw-text-opacity": "1",
    "color": "rgb(255 255 255/var(--tw-text-opacity))"
  },
  ".brutal-btn-teal:hover": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(27 134 126/var(--tw-bg-opacity))"
  },
  ".brutal-btn-teal:active": {
    "--tw-bg-opacity": "1",
    "backgroundColor": "rgb(25 108 102/var(--tw-bg-opacity))"
  },
  ".brutal-btn-border-sm": {
    "borderStyle": "solid",
    "borderWidth": "1px"
  },
  ".brutal-btn-border": {
    "borderStyle": "solid",
    "borderWidth": "2px"
  }
};

export default styles;
