/* eslint-disable */
// THIS FILE IS GENERATED BY `scripts/build-jss.ts`
// DO NOT EDIT THIS FILE DIRECTLY

const styles: any = {
  ".absolute-center": {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate3d(-50%, -50%, 0)",
  },
  ".flex-center": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  ".brutal-shadow-sm": {
    boxShadow: "2px 2px 0px rgba(0, 0, 0, 1)",
  },
  ".brutal-shadow": {
    boxShadow: "4px 4px 0px rgba(0, 0, 0, 1)",
  },
  ".no-drag": {
    WebkitUserDrag: "none",
    KhtmlUserDrag: "none",
    MozUserDrag: "none",
    OUserDrag: "none",
    msUserDrag: "none",
    userDrag: "none",
  },
  ".no-select": {
    WebkitUserSelect: "none",
    KhtmlUserSelect: "none",
    MozUserSelect: "none",
    OUserSelect: "none",
    msUserSelect: "none",
    userSelect: "none",
  },
};

export default styles;
