name: Deploy message-sender Service

on:
  push:
    branches:
      - main
      - releases/main
    paths:
      - services/message-sender/**
      - .github/workflows/deploy-message-sender-service.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        working-directory: services/message-sender
        run: pnpm install --frozen-lockfile

      - name: Some check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/releases/main" ]; then
            echo "::set-output name=env::production"
          else
            echo "::set-output name=env::staging"
          fi

      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: stable
          profile: minimal

      - name: Install worker-build
        uses: actions-rs/install@v0.1
        with:
          crate: worker-build
          use-tool-cache: true

      - name: Publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        working-directory: services/message-sender
        run: pnpm wrangler publish --env ${{ steps.branch_check.outputs.env }}
