name: Deploy to GCP

on:
  push:
    branches:
      - releases/main

env:
  SITE_DIST_FOLDER: "./apps/portfolio/dist"
  SITE_BUCKET_NAME: "www.nurliman.dev"

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: "7"

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: "Validate directory not empty"
        run: '[ "$(ls -A ${{ env.SITE_DIST_FOLDER }})" ] && echo "Files exist - all good." || (echo "Directory is empty - aborting." && exit 1)'

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "${{ secrets.GCP_WIF_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Upload Site"
        run: "gsutil -m rsync -d -r ${{ env.SITE_DIST_FOLDER }} gs://${{ env.SITE_BUCKET_NAME }}"
